"""initial_schema

Revision ID: 6eb961e36b55
Revises: 
Create Date: 2026-08-19 20:14:56.410545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb961e36b55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kiz_operations', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))
    op.alter_column('kiz_product_info', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('orders', 'supply_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_orders_wb_status'), 'orders', ['wb_status'], unique=False)
    op.alter_column('supplies', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplies', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))
    op.drop_index(op.f('ix_orders_wb_status'), table_name='orders')
    op.alter_column('orders', 'supply_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('kiz_product_info', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('kiz_operations', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))
    # ### end Alembic commands ###
